version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_csv:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_dta:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format dta
    outputs:
      highly_sensitive:
        cohort: output/input.dta

  generate_study_population_feather:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  generate_study_population_csv_gz:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz